CREATE TABLE PRODUCTS(
PRODUCT_ID VARCHAR(100) PRIMARY KEY,
PRODUCT_NAME VARCHAR(100),
PRODUCT_DESCRIPTION VARCHAR(100),
PRICE VARCHAR(20)
);


CREATE TABLE PRODUCT_CATEGORY(
CATEGORY_ID VARCHAR(100) PRIMARY KEY,
PRODUCT_ID VARCHAR(100),
CATEGORY_NAME VARCHAR(100)
);


SELECT * FROM PRODUCTS;
SELECT * FROM PRODUCT_CATEGORY;

ALTER TABLE PRODUCTS
RENAME COLUMN PRICE TO PRODUCT_PRICE;



INSERT INTO PRODUCTS VALUES ('SAM001','SAMSUNG GALAXY A51','SAMSUNG GALAXY A51 HAS QUALITY CAMERA','2000.40');
INSERT INTO PRODUCTS VALUES ('HP002','HP LAPTOP','HP LAPTOPS ARE AFFORDABLE AND EASY TO USE','7500.55');
INSERT INTO PRODUCTS VALUES ('LG003','LG TELEVISION','LG TELEVISIONS ARE VERY STRONG AND AFFORDABLE','4750.77');

INSERT INTO PRODUCT_CATEGORY VALUES ('PHONE001','SAM001','PHONES');
INSERT INTO PRODUCT_CATEGORY VALUES ('LAPTOP002','HP002','LAPTOPS');
INSERT INTO PRODUCT_CATEGORY VALUES ('TV003','LG003','TELEVISIONS');

UPDATE PRODUCTS
SET PRODUCT_PRICE = 15000.22
WHERE PRODUCT_ID = 'HP002';