
-- CREATING A TABLE PRODUCTS
create table PRODUCTS(
PRODUCT_ID varchar(100) primary KEY,
PRODUCT_NAME VARCHAR(100),
PRODUCT_DESCRIPTION VARCHAR(100),
PRICE numeric(50)

);

DROP table PRODUCTS;

-- CREATING TABLE PRODUCT_CATEGORY

create table PRODUCT_CATEGORY(
CATEGORY_ID varchar(100) primary KEY,
PRODUCT_ID VARCHAR(100),
CATEGORY_NAME VARCHAR(100),
constraint FK_PRODUCT_ID FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- RENAME COLUMN PRICE
select* from PRODUCTS;
alter table PRODUCTS
rename column PRICE TO PRODUCT_PRICE;

select * FROM PRODUCTS;
INSERT INTO PRODUCTS VALUES('SAM001','SAMSUNG GALAXY AS1', 'SAMSUNG GALAXY AS1 HAS QUALITY CAMERA', '2000.40');
INSERT INTO PRODUCTS VALUES('HP002','HP LAPTOPS', 'HP LAPTOPS ARE AFFORDABLE AND EASY TO USE', '7500.55');
INSERT INTO PRODUCTS VALUES('LG003','LG TELEVISION', 'LG TELEVIONS ARE VERY STRONG AND AFFORDABLE', '4750.77');

select* FROM product_category;
insert INTO product_category VALUES('PHONE001', 'SAM001', 'PHONES');
insert INTO product_category VALUES('LAPTOP002', 'HP002', 'LAPTOPS');
insert INTO product_category VALUES('TV003', 'LG003', 'TELEVIONS');

-- CHANGING PRICE OF HP LAPTOPS
update products
SET PRODUCT_PRICE = '15000.22'
WHERE PRODUCT_ID = 'HP002';

-- select* from products, product_category
-- where products.PRODUCT_ID = product_category.PRODUCT_ID
-- and products.product_ID = 'SAM001';


