CREATE TABLE PRODUCTS (
    PRODUCT_ID int NOT NULL,
    PRODUCT_NAME varchar(255) NOT NULL,
    PRODUCT_DESCRIPTION varchar(255),
    PRICE int,
    PRIMARY KEY (PRODUCT_ID)
); 

CREATE TABLE PRODUCT_CATEGORY (
    CATEGORY_ID int NOT NULL,
    PRODUCT_ID int,
    CATEGORY_NAME varchar(255),
    PRIMARY KEY (CATEGORY_ID)
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
   )

ALTER TABLE PRODUCTS RENAME PRICE TO PRODUCT_PRICE;

INSERT INTO 
	PRODUCTS(PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRICE)
VALUES
	('SAM001','SAMSUNG GALAXY A51','SAMSUNG GALAXY A51 HAS QUALITY CAMERA','2000.40'),
	('HP002','HP LAPTOP','HP LAPTOPS ARE AFFORDABLE AND EASY TO USE','7500.55');
	('LG003','LG TELEVISION','LG TELEVISONS ARE VERY STRONG AND AFFRODABLE','4750.77');

INSERT INTO 
	PRODUCT_CATEGORY (CATEGORY_ID, PRODUCT_ID, CATEGORY_NAME)
VALUES
	('PHONE001','SAM001','PHONES'),
	('LAPTOP002','HP002','LAPTOPS');
	('TV003','LG003','TELEVISIONS');

SELECT 
    PRODUCT_ID,
    PRODUCT_NAME,
    PRODUCT_DESCRIPTION,
    PRICE
FROM
    PRODUCTS
WHERE
    PRODUCT_ID = HP002;


UPDATE PRODUCTS 
SET 
    PRICE = '15000.22'
WHERE
    PRODUCT_ID = HP002;





