
CREATE TABLE `products`. ( `product_id` INT NULL , 
			`product_name` VARCHAR(20) NOT NULL , 
            `product_description` VARCHAR(50) NOT NULL , 
            `price` DECIMAL(10,2) NOT NULL , 
            PRIMARY KEY (`product_id`));

ALTER TABLE `products` CHANGE `price` `PRODUCT_PRICE` DECIMAL(10,2) NOT NULL;

CREATE TABLE `ecom`.`products_category` 
( `CATEGORY _ID` INT(11) NOT NULL AUTO_INCREMENT , 
`PRODUCT_ID` INT(11) NOT NULL , 
`CATEGORY_NAME` VARCHAR(20) NOT NULL , 
PRIMARY KEY (`CATEGORY _ID`));


INSERT INTO `products_category` (`CATEGORY _ID`, `PRODUCT_ID`, `CATEGORY_NAME`) 
VALUES 
(NULL, 'PHONE001', 'PHONE'), (NULL, 'LAPTOP002', 'LAPTOP'), (NULL, 'TV003', 'TV');



INSERT INTO `products` (`PRODUCT_ID`, `PRODUCT_NAME`, `PRODUCT_DESCRIPTION`, `PRODUCT_PRICE`) 
VALUES 
(NULL, 'SAMSUNG GALAXY A51', 'SAMSUNG GALAXY A51 HAS QUALITY GOODS', '2000.40'), 
(NULL, 'HP LAPTOP', 'HP LAPTOP ARE AFFORDABLE AND EASY TO USE', '7500.55'), 
(NULL, 'LG TELEVISIONS', 'LG TELEVISIONS ARE VERY STRONG', '4750.77');

UPDATE `products` SET `PRODUCT_PRICE` = '15000.22' WHERE `products`.`PRODUCT_ID` = 2;