
--CLASS TEST

CREATE TABLE PRODUCTS(
    PRODUCT_ID VARCHAR (50) PRIMARY KEY,
    PRODUCT_NAME VARCHAR (100),
    PRODUCT_DESCRIPTION VARCHAR (100),
    PRICE NUMBER (10,5)
    
);

SELECT * FROM PRODUCTS;

DROP TABLE PRODUCTS;
INSERT INTO PRODUCTS VALUES('SAM001', 'SAMSUNG GALAXY A51', 'SAMSUNG GALAXY A51 HAS QUALITY CAMERA', 2000.40);
INSERT INTO PRODUCTS VALUES('HP002', 'HP LAPTOP', 'HP LAPTOPS ARE AFFORDABLE AND EASY TO USE', 7500.55);
INSERT INTO PRODUCTS VALUES('LG003', 'LG TELEVISION', 'LG TELEVISIONS ARE VERY STRONG AND AFFORDABLE', 4750.77);

ALTER TABLE PRODUCTS
RENAME COLUMN PRICE TO PRODUCT_PRICE;

UPDATE PRODUCTS
SET PRODUCT_PRICE = 15000.22
WHERE product_id = 'HP002';




CREATE TABLE PRODUCTS_CATEGORY(
    CATEGORY_ID VARCHAR (20) PRIMARY KEY,
    PRODUCT_ID VARCHAR (50),
    CATEGORY_NAME VARCHAR (50),
    CONSTRAINT FK_PRODUCT_ID FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE
);

SELECT * FROM PRODUCTS_CATEGORY;

DROP TABLE PRODUCTS_CATEGORY;

INSERT INTO PRODUCTS_CATEGORY VALUES('PHONE001', 'SAM001', 'PHONES');
INSERT INTO PRODUCTS_CATEGORY VALUES('LAPTOP002', 'HP002', 'LAPTOPS');
INSERT INTO PRODUCTS_CATEGORY VALUES('TV003', 'LG003', 'TELEVISION');
